name: 'direnv-nix-action test'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install direnv
      uses: ./

    - name: Check installed direnv tools
      run: which act # this program comes from the flake

    - name: Check environment variables
      run: |
        if [ -z "${PRJ_ROOT}" ]; then
          echo "Error: The environment variable VARIABLE_NAME is not set." >&2
          exit 1
        fi
        echo "Current PRJ_ROOT: ${PRJ_ROOT}"
